//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.SmsServiceLib {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsServiceLib.SMSServiceSoap")]
    public interface SMSServiceSoap {
        
        // CODEGEN: Generating message contract since element name SMS_AuthKey from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        WebApplication1.SmsServiceLib.SendSMSResponse SendSMS(WebApplication1.SmsServiceLib.SendSMSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSMS", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication1.SmsServiceLib.SendSMSResponse> SendSMSAsync(WebApplication1.SmsServiceLib.SendSMSRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMS", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SmsServiceLib.SendSMSRequestBody Body;
        
        public SendSMSRequest() {
        }
        
        public SendSMSRequest(WebApplication1.SmsServiceLib.SendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SMS_AuthKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public long MobileNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        public SendSMSRequestBody() {
        }
        
        public SendSMSRequestBody(string SMS_AuthKey, long MobileNo, string message) {
            this.SMS_AuthKey = SMS_AuthKey;
            this.MobileNo = MobileNo;
            this.message = message;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebApplication1.SmsServiceLib.SendSMSResponseBody Body;
        
        public SendSMSResponse() {
        }
        
        public SendSMSResponse(WebApplication1.SmsServiceLib.SendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSMSResult;
        
        public SendSMSResponseBody() {
        }
        
        public SendSMSResponseBody(string SendSMSResult) {
            this.SendSMSResult = SendSMSResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SMSServiceSoapChannel : WebApplication1.SmsServiceLib.SMSServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SMSServiceSoapClient : System.ServiceModel.ClientBase<WebApplication1.SmsServiceLib.SMSServiceSoap>, WebApplication1.SmsServiceLib.SMSServiceSoap {
        
        public SMSServiceSoapClient() {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SMSServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication1.SmsServiceLib.SendSMSResponse WebApplication1.SmsServiceLib.SMSServiceSoap.SendSMS(WebApplication1.SmsServiceLib.SendSMSRequest request) {
            return base.Channel.SendSMS(request);
        }
        
        public string SendSMS(string SMS_AuthKey, long MobileNo, string message) {
            WebApplication1.SmsServiceLib.SendSMSRequest inValue = new WebApplication1.SmsServiceLib.SendSMSRequest();
            inValue.Body = new WebApplication1.SmsServiceLib.SendSMSRequestBody();
            inValue.Body.SMS_AuthKey = SMS_AuthKey;
            inValue.Body.MobileNo = MobileNo;
            inValue.Body.message = message;
            WebApplication1.SmsServiceLib.SendSMSResponse retVal = ((WebApplication1.SmsServiceLib.SMSServiceSoap)(this)).SendSMS(inValue);
            return retVal.Body.SendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication1.SmsServiceLib.SendSMSResponse> WebApplication1.SmsServiceLib.SMSServiceSoap.SendSMSAsync(WebApplication1.SmsServiceLib.SendSMSRequest request) {
            return base.Channel.SendSMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication1.SmsServiceLib.SendSMSResponse> SendSMSAsync(string SMS_AuthKey, long MobileNo, string message) {
            WebApplication1.SmsServiceLib.SendSMSRequest inValue = new WebApplication1.SmsServiceLib.SendSMSRequest();
            inValue.Body = new WebApplication1.SmsServiceLib.SendSMSRequestBody();
            inValue.Body.SMS_AuthKey = SMS_AuthKey;
            inValue.Body.MobileNo = MobileNo;
            inValue.Body.message = message;
            return ((WebApplication1.SmsServiceLib.SMSServiceSoap)(this)).SendSMSAsync(inValue);
        }
    }
}
